module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    SALES_REP: 'SALES_REP',
    SALES_MANAGER: 'SALES_MANAGER',
    FINANCE: 'FINANCE',
    OPERATIONS: 'OPERATIONS',
    CUSTOMER: 'CUSTOMER'
  },
  QUOTATION_STATUS: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    REVISION_REQUIRED: 'REVISION_REQUIRED',
    RE_APPROVAL_REQUIRED: 'RE_APPROVAL_REQUIRED',
    SENT: 'SENT',
    NEGOTIATION: 'NEGOTIATION',
    CONFIRMED: 'CONFIRMED',
    FULFILLING: 'FULFILLING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  APPROVAL_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    REVISION_REQUIRED: 'REVISION_REQUIRED'
  },
  RISK_LEVEL: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL'
  },
  INVOICE_STATUS: {
    DRAFT: 'DRAFT',
    SENT: 'SENT',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    PAID: 'PAID',
    OVERDUE: 'OVERDUE',
    CANCELLED: 'CANCELLED'
  }
};
