// Realistic enterprise mock dataset for DealFlow360 Sales Operations Cockpit

export const INITIAL_CUSTOMERS = [
  {
    id: 1,
    name: 'Acme Corporation',
    tier: 'Gold',
    industry: 'Enterprise Software',
    contact_person: 'Sarah Jenkins',
    email: 'sjenkins@acmecorp.com',
    phone: '+1 (555) 234-5678',
    billing_address: '100 Enterprise Way, Suite 400, Austin, TX 78701',
    shipping_address: '100 Enterprise Way, Suite 400, Austin, TX 78701',
    price_list: 'Enterprise Gold Tier (USD)',
    payment_terms: 'Net 30',
    max_discount: 15
  },
  {
    id: 2,
    name: 'Nova Technologies',
    tier: 'Silver',
    industry: 'Fintech & Payments',
    contact_person: 'Marcus Vance',
    email: 'mvance@novatech.io',
    phone: '+1 (555) 345-6789',
    billing_address: '450 Silicon Blvd, Floor 12, San Francisco, CA 94107',
    shipping_address: '450 Silicon Blvd, Floor 12, San Francisco, CA 94107',
    price_list: 'Commercial Silver Tier (USD)',
    payment_terms: 'Net 45',
    max_discount: 10
  },
  {
    id: 3,
    name: 'TechCorp International',
    tier: 'Platinum',
    industry: 'Cloud Infrastructure',
    contact_person: 'Elena Rostova',
    email: 'erostova@techcorp.com',
    phone: '+1 (555) 456-7890',
    billing_address: '750 Innovation Dr, Seattle, WA 98101',
    shipping_address: '750 Innovation Dr, Seattle, WA 98101',
    price_list: 'Global Platinum Partner (USD)',
    payment_terms: 'Net 60',
    max_discount: 20
  },
  {
    id: 4,
    name: 'Delta Logistics LLC',
    tier: 'Bronze',
    industry: 'Supply Chain & Freight',
    contact_person: 'David Chen',
    email: 'dchen@deltalogistics.com',
    phone: '+1 (555) 567-8901',
    billing_address: '88 Logistics Parkway, Atlanta, GA 30320',
    shipping_address: '88 Logistics Parkway, Atlanta, GA 30320',
    price_list: 'Standard Base (USD)',
    payment_terms: 'Net 30',
    max_discount: 5
  },
  {
    id: 5,
    name: 'Zenith Health Systems',
    tier: 'Gold',
    industry: 'Healthcare & Life Sciences',
    contact_person: 'Dr. Robert Torres',
    email: 'rtorres@zenithhealth.org',
    phone: '+1 (555) 678-9012',
    billing_address: '12 Medical Center Blvd, Boston, MA 02115',
    shipping_address: '12 Medical Center Blvd, Boston, MA 02115',
    price_list: 'Enterprise Gold Tier (USD)',
    payment_terms: 'Net 30',
    max_discount: 15
  },
  {
    id: 6,
    name: 'Apex Global Capital',
    tier: 'Platinum',
    industry: 'Investment Banking',
    contact_person: 'Victoria Sterling',
    email: 'vsterling@apexcapital.com',
    phone: '+1 (555) 789-0123',
    billing_address: '200 Wall Street, 24th Floor, New York, NY 10005',
    shipping_address: '200 Wall Street, 24th Floor, New York, NY 10005',
    price_list: 'Global Platinum Partner (USD)',
    payment_terms: 'Net 15',
    max_discount: 20
  },
  {
    id: 7,
    name: 'Meridian Media Group',
    tier: 'Silver',
    industry: 'Broadcast & Media',
    contact_person: 'Liam O’Connor',
    email: 'loconnor@meridianmg.com',
    phone: '+1 (555) 890-1234',
    billing_address: '500 Sunset Blvd, Los Angeles, CA 90028',
    shipping_address: '500 Sunset Blvd, Los Angeles, CA 90028',
    price_list: 'Commercial Silver Tier (USD)',
    payment_terms: 'Net 30',
    max_discount: 10
  },
  {
    id: 8,
    name: 'Pinnacle Manufacturing',
    tier: 'Bronze',
    industry: 'Heavy Industry & Aerospace',
    contact_person: 'Thomas Wright',
    email: 'twright@pinnaclemfg.com',
    phone: '+1 (555) 901-2345',
    billing_address: '320 Industrial Rd, Detroit, MI 48201',
    shipping_address: '320 Industrial Rd, Detroit, MI 48201',
    price_list: 'Standard Base (USD)',
    payment_terms: 'Net 45',
    max_discount: 5
  },
  {
    id: 9,
    name: 'Horizon Energy Group',
    tier: 'Gold',
    industry: 'Renewables & Utilities',
    contact_person: 'Claire Fontaine',
    email: 'cfontaine@horizonenergy.com',
    phone: '+1 (555) 012-3456',
    billing_address: '77 Clean Energy Ave, Denver, CO 80202',
    shipping_address: '77 Clean Energy Ave, Denver, CO 80202',
    price_list: 'Enterprise Gold Tier (USD)',
    payment_terms: 'Net 30',
    max_discount: 15
  },
  {
    id: 10,
    name: 'Omni Retail Ventures',
    tier: 'Silver',
    industry: 'E-Commerce & Omnichannel',
    contact_person: 'Ananya Sharma',
    email: 'asharma@omniretail.com',
    phone: '+1 (555) 123-4567',
    billing_address: '140 Commerce Way, Chicago, IL 60601',
    shipping_address: '140 Commerce Way, Chicago, IL 60601',
    price_list: 'Commercial Silver Tier (USD)',
    payment_terms: 'Net 30',
    max_discount: 10
  }
];

export const INITIAL_PRODUCTS = [
  { id: 1, name: 'Laptop Pro 14', sku: 'HW-LP-14', category: 'Hardware', unit_price: 2400, unit_cost: 1600, max_discount: 15, stock: 48, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 3, updated_at: '2026-09-04T12:00:00Z' },
  { id: 2, name: 'Laptop Pro 16 Max', sku: 'HW-LP-16', category: 'Hardware', unit_price: 3200, unit_cost: 2100, max_discount: 15, stock: 32, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 2, updated_at: '2026-09-03T11:00:00Z' },
  { id: 3, name: 'Enterprise Workstation Z8', sku: 'HW-WS-Z8', category: 'Hardware', unit_price: 4500, unit_cost: 2900, max_discount: 12, stock: 15, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 4, updated_at: '2026-09-02T15:30:00Z' },
  { id: 4, name: 'Thunderbolt Docking Station', sku: 'HW-DK-04', category: 'Hardware', unit_price: 280, unit_cost: 160, max_discount: 15, stock: 120, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 2, updated_at: '2026-09-01T09:00:00Z' },
  { id: 5, name: 'Wireless Ergonomic Mouse & Keyboard', sku: 'HW-AC-02', category: 'Accessories', unit_price: 120, unit_cost: 65, max_discount: 20, stock: 250, billing_type: 'ONE_TIME', unit: 'Set', status: 'Active', variants: 1, updated_at: '2026-08-30T10:00:00Z' },
  { id: 6, name: 'Onsite Deployment & Setup', sku: 'SV-STP-01', category: 'Services', unit_price: 450, unit_cost: 220, max_discount: 10, stock: 999, billing_type: 'ONE_TIME', unit: 'Hour', status: 'Active', variants: 0, updated_at: '2026-08-28T14:20:00Z' },
  { id: 7, name: 'Executive Architecture Consulting', sku: 'SV-CNS-01', category: 'Services', unit_price: 2500, unit_cost: 1200, max_discount: 10, stock: 999, billing_type: 'ONE_TIME', unit: 'Day', status: 'Active', variants: 0, updated_at: '2026-08-25T16:00:00Z' },
  { id: 8, name: 'Care Plan 2yr (Extended Warranty + SLA)', sku: 'SB-CR-2Y', category: 'Subscription', unit_price: 46, unit_cost: 18, max_discount: 10, stock: 999, billing_type: 'RECURRING', frequency: 'Monthly', unit: 'Month', status: 'Active', variants: 0, updated_at: '2026-08-22T08:30:00Z' },
  { id: 9, name: 'Enterprise Support SLA 24/7', sku: 'SB-SLA-24', category: 'Subscription', unit_price: 300, unit_cost: 110, max_discount: 10, stock: 999, billing_type: 'RECURRING', frequency: 'Monthly', unit: 'Month', status: 'Active', variants: 0, updated_at: '2026-08-20T17:00:00Z' },
  { id: 10, name: 'Managed Endpoint Security Suite', sku: 'SB-SEC-01', category: 'Subscription', unit_price: 25, unit_cost: 9, max_discount: 12, stock: 999, billing_type: 'RECURRING', frequency: 'Monthly', unit: 'User/Mo', status: 'Active', variants: 0, updated_at: '2026-08-18T10:15:00Z' },
  { id: 11, name: 'Ultra-Wide 34" Curved Monitor', sku: 'HW-MN-34', category: 'Hardware', unit_price: 850, unit_cost: 540, max_discount: 15, stock: 65, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 2, updated_at: '2026-08-15T11:45:00Z' },
  { id: 12, name: 'Server Rackmount Node 2U', sku: 'HW-SRV-2U', category: 'Hardware', unit_price: 6800, unit_cost: 4400, max_discount: 10, stock: 12, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 2, updated_at: '2026-08-12T13:00:00Z' },
  { id: 13, name: 'Network Switch 48-Port PoE+', sku: 'HW-NET-48', category: 'Hardware', unit_price: 1850, unit_cost: 1150, max_discount: 15, stock: 24, billing_type: 'ONE_TIME', unit: 'Each', status: 'Active', variants: 1, updated_at: '2026-08-10T09:30:00Z' },
  { id: 14, name: 'Data Migration & Pipeline Integration', sku: 'SV-MIG-01', category: 'Services', unit_price: 3800, unit_cost: 1900, max_discount: 10, stock: 999, billing_type: 'ONE_TIME', unit: 'Project', status: 'Active', variants: 0, updated_at: '2026-08-08T15:00:00Z' },
  { id: 15, name: 'Annual Training & Onboarding Pack', sku: 'SV-TRN-01', category: 'Services', unit_price: 1500, unit_cost: 600, max_discount: 15, stock: 999, billing_type: 'ONE_TIME', unit: 'Package', status: 'Active', variants: 0, updated_at: '2026-08-05T14:00:00Z' }
];

export const INITIAL_DISCOUNT_RULES = {
  tier_ceilings: {
    Bronze: 5,
    Silver: 10,
    Gold: 15,
    Enterprise: 20,
    Platinum: 20
  },
  category_ceilings: {
    Hardware: 15,
    Services: 10,
    Cloud: 12,
    Software: 15,
    Subscription: 10,
    Accessories: 20
  },
  margin_floor: {
    target: 30,
    minimum: 25
  },
  approval_matrix: [
    { condition: 'Within tier and category limit', action: 'No approval needed', level: 'SALES_REP', color: 'emerald' },
    { condition: 'Over limit, blended risk medium (40-69)', action: 'Sales Manager Approval', level: 'SALES_MANAGER', color: 'blue' },
    { condition: 'Over limit, blended high risk (70+) or margin < 25%', action: 'Sales Manager then Finance Approval', level: 'FINANCE', color: 'purple' }
  ]
};

export const INITIAL_QUOTATIONS = [
  {
    id: 1,
    quotation_number: 'Q-104',
    customer_id: 1,
    customer_name: 'Acme Corporation',
    customer_tier: 'Gold',
    total_amount: 92000,
    subtotal: 105000,
    discount_amount: 19500,
    tax_amount: 6500,
    gross_margin_pct: 24.2,
    discount_pct: 22.0,
    discount_limit: 15.0,
    stage: 'PENDING APPROVAL',
    status: 'PENDING APPROVAL',
    health_score: 58,
    health_status: 'AT RISK',
    risk_score: 82,
    risk_level: 'HIGH RISK',
    approval_required: true,
    required_approval_level: 'FINANCE',
    owner: 'Sales Rep',
    created_at: '2026-09-05T08:10:00Z',
    last_activity: '2h ago',
    items: [
      { product_id: 1, product_name: 'Laptop Pro 14', sku: 'HW-LP-14', quantity: 30, unit_price: 2400, unit_cost: 1600, discount_pct: 22, discount_amount: 15840, final_price: 56160, margin_pct: 24.5, limit: 15, violation: true },
      { product_id: 4, product_name: 'Thunderbolt Docking Station', sku: 'HW-DK-04', quantity: 30, unit_price: 280, unit_cost: 160, discount_pct: 15, discount_amount: 1260, final_price: 7140, margin_pct: 32.8, limit: 15, violation: false },
      { product_id: 6, product_name: 'Onsite Deployment & Setup', sku: 'SV-STP-01', category: 'Services', quantity: 40, unit_price: 450, unit_cost: 220, discount_pct: 12, discount_amount: 2160, final_price: 15840, margin_pct: 44.4, limit: 10, violation: true }
    ],
    risk_breakdown: {
      discount_risk: 30,
      margin_risk: 25,
      deal_size_risk: 15,
      inactivity_risk: 12,
      total: 82
    },
    recommendations: [
      {
        id: 'rec-1',
        title: 'Discount Optimization',
        description: 'Reduce discount from 22% to 15% on Laptop Pro 14 to protect approximately $6,440 in gross margin and bypass Finance approval escalation.',
        target_discount: 15,
        target_product_id: 1,
        savings: 6440
      }
    ]
  },
  {
    id: 2,
    quotation_number: 'Q-105',
    customer_id: 2,
    customer_name: 'Nova Technologies',
    customer_tier: 'Silver',
    total_amount: 48000,
    subtotal: 51000,
    discount_amount: 4500,
    tax_amount: 1500,
    gross_margin_pct: 34.0,
    discount_pct: 8.8,
    discount_limit: 10.0,
    stage: 'NEGOTIATION',
    status: 'NEGOTIATION',
    health_score: 87,
    health_status: 'HEALTHY',
    risk_score: 24,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-09-05T09:30:00Z',
    last_activity: '1h ago',
    items: [
      { product_id: 2, product_name: 'Laptop Pro 16 Max', sku: 'HW-LP-16', quantity: 15, unit_price: 3200, unit_cost: 2100, discount_pct: 8.8, discount_amount: 4224, final_price: 43776, margin_pct: 34.0, limit: 10, violation: false }
    ],
    risk_breakdown: { discount_risk: 5, margin_risk: 8, deal_size_risk: 7, inactivity_risk: 4, total: 24 },
    recommendations: []
  },
  {
    id: 3,
    quotation_number: 'Q-106',
    customer_id: 3,
    customer_name: 'TechCorp International',
    customer_tier: 'Platinum',
    total_amount: 125000,
    subtotal: 138000,
    discount_amount: 18000,
    tax_amount: 5000,
    gross_margin_pct: 31.0,
    discount_pct: 13.0,
    discount_limit: 20.0,
    stage: 'DRAFT',
    status: 'DRAFT',
    health_score: 92,
    health_status: 'HEALTHY',
    risk_score: 18,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-09-05T10:15:00Z',
    last_activity: '20m ago',
    items: [
      { product_id: 3, product_name: 'Enterprise Workstation Z8', sku: 'HW-WS-Z8', quantity: 20, unit_price: 4500, unit_cost: 2900, discount_pct: 13.0, discount_amount: 11700, final_price: 78300, margin_pct: 31.0, limit: 20, violation: false }
    ],
    risk_breakdown: { discount_risk: 4, margin_risk: 6, deal_size_risk: 5, inactivity_risk: 3, total: 18 },
    recommendations: []
  },
  {
    id: 4,
    quotation_number: 'Q-107',
    customer_id: 5,
    customer_name: 'Zenith Health Systems',
    customer_tier: 'Gold',
    total_amount: 64500,
    subtotal: 72000,
    discount_amount: 11000,
    tax_amount: 3500,
    gross_margin_pct: 26.5,
    discount_pct: 18.0,
    discount_limit: 15.0,
    stage: 'PENDING APPROVAL',
    status: 'PENDING APPROVAL',
    health_score: 62,
    health_status: 'WATCH',
    risk_score: 68,
    risk_level: 'MEDIUM RISK',
    approval_required: true,
    required_approval_level: 'SALES_MANAGER',
    owner: 'Sales Rep',
    created_at: '2026-09-04T11:00:00Z',
    last_activity: '1d ago',
    items: [
      { product_id: 1, product_name: 'Laptop Pro 14', sku: 'HW-LP-14', quantity: 25, unit_price: 2400, unit_cost: 1600, discount_pct: 18.0, discount_amount: 10800, final_price: 49200, margin_pct: 26.5, limit: 15, violation: true }
    ],
    risk_breakdown: { discount_risk: 24, margin_risk: 20, deal_size_risk: 14, inactivity_risk: 10, total: 68 },
    recommendations: []
  },
  {
    id: 5,
    quotation_number: 'Q-108',
    customer_id: 6,
    customer_name: 'Apex Global Capital',
    customer_tier: 'Platinum',
    total_amount: 185000,
    subtotal: 195000,
    discount_amount: 16000,
    tax_amount: 6000,
    gross_margin_pct: 35.8,
    discount_pct: 8.2,
    discount_limit: 20.0,
    stage: 'APPROVED',
    status: 'APPROVED',
    health_score: 95,
    health_status: 'HEALTHY',
    risk_score: 12,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-09-03T14:20:00Z',
    last_activity: '2d ago',
    items: [],
    risk_breakdown: { discount_risk: 3, margin_risk: 4, deal_size_risk: 3, inactivity_risk: 2, total: 12 },
    recommendations: []
  },
  {
    id: 6,
    quotation_number: 'Q-109',
    customer_id: 4,
    customer_name: 'Delta Logistics LLC',
    customer_tier: 'Bronze',
    total_amount: 32400,
    subtotal: 39000,
    discount_amount: 8500,
    tax_amount: 1900,
    gross_margin_pct: 21.0,
    discount_pct: 21.8,
    discount_limit: 5.0,
    stage: 'PENDING APPROVAL',
    status: 'PENDING APPROVAL',
    health_score: 38,
    health_status: 'CRITICAL',
    risk_score: 88,
    risk_level: 'HIGH RISK',
    approval_required: true,
    required_approval_level: 'FINANCE',
    owner: 'Sales Rep',
    created_at: '2026-09-02T16:00:00Z',
    last_activity: '3d ago',
    items: [],
    risk_breakdown: { discount_risk: 35, margin_risk: 28, deal_size_risk: 12, inactivity_risk: 13, total: 88 },
    recommendations: []
  },
  {
    id: 7,
    quotation_number: 'Q-110',
    customer_id: 7,
    customer_name: 'Meridian Media Group',
    customer_tier: 'Silver',
    total_amount: 54000,
    subtotal: 58000,
    discount_amount: 5200,
    tax_amount: 1200,
    gross_margin_pct: 33.2,
    discount_pct: 9.0,
    discount_limit: 10.0,
    stage: 'WON',
    status: 'WON',
    health_score: 98,
    health_status: 'HEALTHY',
    risk_score: 10,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-09-01T09:00:00Z',
    last_activity: '4d ago',
    items: [],
    risk_breakdown: { discount_risk: 2, margin_risk: 3, deal_size_risk: 3, inactivity_risk: 2, total: 10 },
    recommendations: []
  },
  {
    id: 8,
    quotation_number: 'Q-111',
    customer_id: 8,
    customer_name: 'Pinnacle Manufacturing',
    customer_tier: 'Bronze',
    total_amount: 76000,
    subtotal: 78000,
    discount_amount: 3500,
    tax_amount: 1500,
    gross_margin_pct: 32.0,
    discount_pct: 4.5,
    discount_limit: 5.0,
    stage: 'WON',
    status: 'WON',
    health_score: 91,
    health_status: 'HEALTHY',
    risk_score: 15,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-08-30T10:00:00Z',
    last_activity: '6d ago',
    items: [],
    risk_breakdown: { discount_risk: 3, margin_risk: 5, deal_size_risk: 4, inactivity_risk: 3, total: 15 },
    recommendations: []
  },
  {
    id: 9,
    quotation_number: 'Q-112',
    customer_id: 9,
    customer_name: 'Horizon Energy Group',
    customer_tier: 'Gold',
    total_amount: 115000,
    subtotal: 120000,
    discount_amount: 9000,
    tax_amount: 4000,
    gross_margin_pct: 33.5,
    discount_pct: 7.5,
    discount_limit: 15.0,
    stage: 'CONFIRMED',
    status: 'CONFIRMED',
    health_score: 94,
    health_status: 'HEALTHY',
    risk_score: 14,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-08-28T12:00:00Z',
    last_activity: '8d ago',
    items: [],
    risk_breakdown: { discount_risk: 3, margin_risk: 4, deal_size_risk: 4, inactivity_risk: 3, total: 14 },
    recommendations: []
  },
  {
    id: 10,
    quotation_number: 'Q-113',
    customer_id: 10,
    customer_name: 'Omni Retail Ventures',
    customer_tier: 'Silver',
    total_amount: 42000,
    subtotal: 45000,
    discount_amount: 4000,
    tax_amount: 1000,
    gross_margin_pct: 32.1,
    discount_pct: 8.8,
    discount_limit: 10.0,
    stage: 'NEGOTIATION',
    status: 'NEGOTIATION',
    health_score: 75,
    health_status: 'WATCH',
    risk_score: 35,
    risk_level: 'LOW RISK',
    approval_required: false,
    required_approval_level: 'SALES_REP',
    owner: 'Sales Rep',
    created_at: '2026-08-25T15:00:00Z',
    last_activity: '3d ago',
    items: [],
    risk_breakdown: { discount_risk: 8, margin_risk: 10, deal_size_risk: 9, inactivity_risk: 8, total: 35 },
    recommendations: []
  },
  {
    id: 11,
    quotation_number: 'Q-114',
    customer_id: 1,
    customer_name: 'Acme Corporation',
    customer_tier: 'Gold',
    total_amount: 38000,
    subtotal: 42000,
    discount_amount: 5500,
    tax_amount: 1500,
    gross_margin_pct: 29.0,
    discount_pct: 13.0,
    discount_limit: 15.0,
    stage: 'PENDING APPROVAL',
    status: 'PENDING APPROVAL',
    health_score: 71,
    health_status: 'WATCH',
    risk_score: 45,
    risk_level: 'MEDIUM RISK',
    approval_required: true,
    required_approval_level: 'SALES_MANAGER',
    owner: 'Sales Rep',
    created_at: '2026-08-22T11:00:00Z',
    last_activity: '5d ago',
    items: [],
    risk_breakdown: { discount_risk: 15, margin_risk: 14, deal_size_risk: 8, inactivity_risk: 8, total: 45 },
    recommendations: []
  },
  {
    id: 12,
    quotation_number: 'Q-115',
    customer_id: 2,
    customer_name: 'Nova Technologies',
    customer_tier: 'Silver',
    total_amount: 88000,
    subtotal: 95000,
    discount_amount: 9000,
    tax_amount: 2000,
    gross_margin_pct: 28.5,
    discount_pct: 9.5,
    discount_limit: 10.0,
    stage: 'NEGOTIATION',
    status: 'NEGOTIATION',
    health_score: 34,
    health_status: 'CRITICAL',
    risk_score: 74,
    risk_level: 'HIGH RISK',
    approval_required: true,
    required_approval_level: 'SALES_MANAGER',
    owner: 'Sales Rep',
    created_at: '2026-08-15T09:00:00Z',
    last_activity: '8d ago',
    items: [],
    risk_breakdown: { discount_risk: 14, margin_risk: 18, deal_size_risk: 16, inactivity_risk: 26, total: 74 },
    recommendations: []
  }
];

export const INITIAL_APPROVALS = [
  {
    id: 1,
    quotation_id: 1,
    quotation_number: 'Q-104',
    customer_name: 'Acme Corporation',
    value: 92000,
    discount_pct: 22.0,
    margin_pct: 24.2,
    risk_score: 82,
    risk_level: 'HIGH RISK',
    reason: 'Discount above ceiling (22% vs 15% limit)',
    required_role: 'FINANCE',
    stage: 'Finance Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-09-05T08:15:00Z'
  },
  {
    id: 2,
    quotation_id: 4,
    quotation_number: 'Q-107',
    customer_name: 'Zenith Health Systems',
    value: 64500,
    discount_pct: 18.0,
    margin_pct: 26.5,
    risk_score: 68,
    risk_level: 'MEDIUM RISK',
    reason: 'Hardware discount 18% exceeds 15% limit',
    required_role: 'SALES_MANAGER',
    stage: 'Sales Manager Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-09-04T11:05:00Z'
  },
  {
    id: 3,
    quotation_id: 6,
    quotation_number: 'Q-109',
    customer_name: 'Delta Logistics LLC',
    value: 32400,
    discount_pct: 21.8,
    margin_pct: 21.0,
    risk_score: 88,
    risk_level: 'HIGH RISK',
    reason: 'Critical margin compression (21% vs 30% target)',
    required_role: 'FINANCE',
    stage: 'Finance Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-09-02T16:05:00Z'
  },
  {
    id: 4,
    quotation_id: 11,
    quotation_number: 'Q-114',
    customer_name: 'Acme Corporation',
    value: 38000,
    discount_pct: 13.0,
    margin_pct: 29.0,
    risk_score: 45,
    risk_level: 'MEDIUM RISK',
    reason: 'Cross-category service discount exception',
    required_role: 'SALES_MANAGER',
    stage: 'Sales Manager Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-08-22T11:10:00Z'
  },
  {
    id: 5,
    quotation_id: 12,
    quotation_number: 'Q-115',
    customer_name: 'Nova Technologies',
    value: 88000,
    discount_pct: 9.5,
    margin_pct: 28.5,
    risk_score: 74,
    risk_level: 'HIGH RISK',
    reason: 'Inactivity threshold exceeded (8+ days idle)',
    required_role: 'SALES_MANAGER',
    stage: 'Sales Manager Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-08-20T10:00:00Z'
  },
  {
    id: 6,
    quotation_id: 5,
    quotation_number: 'Q-108',
    customer_name: 'Apex Global Capital',
    value: 185000,
    discount_pct: 8.2,
    margin_pct: 35.8,
    risk_score: 12,
    risk_level: 'LOW RISK',
    reason: 'Standard volume threshold approval',
    required_role: 'SALES_MANAGER',
    stage: 'Approved',
    status: 'APPROVED',
    requested_by: 'Sales Rep',
    created_at: '2026-09-03T14:30:00Z'
  },
  {
    id: 7,
    quotation_id: 7,
    quotation_number: 'Q-110',
    customer_name: 'Meridian Media Group',
    value: 54000,
    discount_pct: 9.0,
    margin_pct: 33.2,
    risk_score: 10,
    risk_level: 'LOW RISK',
    reason: 'Expedited contract sign-off',
    required_role: 'SALES_MANAGER',
    stage: 'Approved',
    status: 'APPROVED',
    requested_by: 'Sales Rep',
    created_at: '2026-09-01T09:15:00Z'
  },
  {
    id: 8,
    quotation_id: 8,
    quotation_number: 'Q-102',
    customer_name: 'Starlight Media',
    value: 19400,
    discount_pct: 28.0,
    margin_pct: 18.5,
    risk_score: 94,
    risk_level: 'HIGH RISK',
    reason: 'Discounts severely exceed negative margin threshold',
    required_role: 'FINANCE',
    stage: 'Rejected',
    status: 'REJECTED',
    requested_by: 'Sales Rep',
    created_at: '2026-08-19T13:00:00Z'
  },
  {
    id: 9,
    quotation_id: 3,
    quotation_number: 'Q-103',
    customer_name: 'TechCorp International',
    value: 45000,
    discount_pct: 14.0,
    margin_pct: 28.0,
    risk_score: 48,
    risk_level: 'MEDIUM RISK',
    reason: 'Non-standard payment terms request',
    required_role: 'SALES_MANAGER',
    stage: 'Sales Manager Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-08-18T14:00:00Z'
  },
  {
    id: 10,
    quotation_id: 9,
    quotation_number: 'Q-101',
    customer_name: 'Horizon Energy Group',
    value: 52000,
    discount_pct: 16.0,
    margin_pct: 27.5,
    risk_score: 52,
    risk_level: 'MEDIUM RISK',
    reason: 'Discretionary partner rebate requested',
    required_role: 'SALES_MANAGER',
    stage: 'Sales Manager Review',
    status: 'PENDING',
    requested_by: 'Sales Rep',
    created_at: '2026-08-17T11:00:00Z'
  }
];

export const INITIAL_AUDIT_EVENTS = [
  { id: 1, quote_id: 1, time: '10:42 AM', action: 'Discount rule evaluated', user: 'System', detail: 'Hardware discount ceiling 15% checked against 22% requested' },
  { id: 2, quote_id: 1, time: '10:43 AM', action: 'Risk score calculated: 82', user: 'System', detail: 'Blended risk: Discount +30, Margin +25, Deal Size +15, Inactivity +12' },
  { id: 3, quote_id: 1, time: '10:44 AM', action: 'Quotation submitted for Finance approval', user: 'Sales Rep', detail: 'Quotation Q-104 routed to Finance review queue' },
  { id: 4, quote_id: 1, time: '10:51 AM', action: 'Finance approval pending', user: 'System', detail: 'SLA timer started: 4 hours remaining' },
  { id: 5, quote_id: 2, time: '09:30 AM', action: 'Quotation created', user: 'Sales Rep', detail: 'Quotation Q-105 created for Nova Technologies' },
  { id: 6, quote_id: 2, time: '09:35 AM', action: 'Customer negotiation started', user: 'Customer Portal', detail: 'Customer reviewed line items and requested Net 45 terms' },
  { id: 7, quote_id: 3, time: '10:15 AM', action: 'Draft quotation saved', user: 'Sales Rep', detail: 'Added 20x Enterprise Workstation Z8' },
  { id: 8, quote_id: 4, time: '11:00 AM', action: 'Sales Manager review triggered', user: 'System', detail: 'Discount 18% on Laptop Pro 14 exceeds Gold tier 15% limit' },
  { id: 9, quote_id: 5, time: '02:30 PM', action: 'Quotation approved by Sales Manager', user: 'Sales Manager', detail: 'Discount 8.2% within acceptable margin corridor' },
  { id: 10, quote_id: 6, time: '04:00 PM', action: 'Margin compression warning generated', user: 'System', detail: 'Gross margin dropped to 21% (below 30% target)' },
  { id: 11, quote_id: 7, time: '09:10 AM', action: 'Deal won and confirmed', user: 'Sales Rep', detail: 'Customer executed contract' },
  { id: 12, quote_id: 8, time: '10:00 AM', action: 'Warehouse split calculated', user: 'Fulfillment Engine', detail: 'Split between Main Warehouse (70%) and East Depot (30%)' },
  { id: 13, quote_id: 9, time: '12:00 PM', action: 'Recurring subscription activated', user: 'Billing Engine', detail: 'SaaS Care Plan scheduled for monthly dispatch' },
  { id: 14, quote_id: 10, time: '03:00 PM', action: 'Terms updated to Net 30', user: 'Finance', detail: 'Customer credit verified' },
  { id: 15, quote_id: 12, time: '09:00 AM', action: 'Deal inactivity flagged (8+ days)', user: 'AI Sentinel', detail: 'Automated nudge queued for sales rep' }
];

export const INITIAL_ANOMALIES = [
  {
    id: 'anom-1',
    quote_number: 'Q-104',
    quote_id: 1,
    customer: 'Acme Corporation',
    title: 'Discount anomaly',
    severity: 'HIGH',
    metric_given: '22%',
    benchmark: '8%',
    description: '14 percentage points above rep average discount.'
  },
  {
    id: 'anom-2',
    quote_number: 'Q-109',
    quote_id: 6,
    customer: 'Delta Logistics LLC',
    title: 'Margin compression',
    severity: 'CRITICAL',
    metric_given: '21%',
    benchmark: '30%',
    description: 'Gross Margin 21% vs target 30% creates negative contribution margin.'
  },
  {
    id: 'anom-3',
    quote_number: 'Q-115',
    quote_id: 12,
    customer: 'Nova Technologies',
    title: 'Deal inactivity',
    severity: 'WATCH',
    metric_given: '8 days',
    benchmark: '3 days',
    description: 'No buyer or seller activity for 8 consecutive days in negotiation.'
  }
];
