CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  amount DECIMAL(14, 2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method ENUM('NEFT', 'RTGS', 'UPI', 'CREDIT_CARD', 'BANK_TRANSFER', 'CHEQUE') NOT NULL DEFAULT 'BANK_TRANSFER',
  transaction_reference VARCHAR(100) NOT NULL,
  status ENUM('SUCCESS', 'FAILED', 'PENDING') NOT NULL DEFAULT 'SUCCESS',
  notes TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
