CREATE TABLE IF NOT EXISTS negotiations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quotation_id INT NOT NULL,
  user_id INT NOT NULL,
  role ENUM('CUSTOMER', 'SALES_REP', 'SALES_MANAGER', 'ADMIN') NOT NULL,
  message_type ENUM('COMMENT', 'COUNTER_OFFER', 'CHANGE_REQUEST', 'SYSTEM_NOTIFICATION') NOT NULL,
  counter_price DECIMAL(14, 2) NULL,
  counter_discount_pct DECIMAL(5, 2) NULL,
  comment TEXT NOT NULL,
  line_changes_json JSON NULL,
  status ENUM('OPEN', 'ACCEPTED', 'REJECTED', 'SUPERSEDED') DEFAULT 'OPEN',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
